"""add email to users

Revision ID: 0f7ad6d264ab
Revises: 6b680c951053
Create Date: 2026-08-31 12:47:07.089966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7ad6d264ab'
down_revision = '6b680c951053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))

    # Backfill existing rows
    op.execute(
        sa.text(
            "UPDATE users "
            "SET email = username || '@example.invalid' "
            "WHERE email is NULL"
        )
    )

    # Make email NOT NULL and add named UNIQUE constraint
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'email',
            existing_type=sa.String(length=150),
            nullable=False,
        )
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
