"""add sync jobs table

Revision ID: 31985462bd6c
Revises: 0f7ad6d264ab
Create Date: 2026-08-31 20:51:22.277550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31985462bd6c'
down_revision = '0f7ad6d264ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('email_address', sa.String(length=150), nullable=False),
    sa.Column('source_todo_id', sa.Integer(), nullable=False),
    sa.Column('todo_title', sa.String(length=108), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_jobs')
    # ### end Alembic commands ###
