"""allow null next attempt for sync jobs

Revision ID: 92f6aa9e8ed7
Revises: 31985462bd6c
Create Date: 2026-09-02 17:00:34.519919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92f6aa9e8ed7'
down_revision = '31985462bd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.alter_column('next_attempt_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.alter_column('next_attempt_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    # ### end Alembic commands ###
